    getgenv().ShirouSettings.HoldKey = false
    getgenv().ShirouSettings.ToggleKey = true
    getgenv().ShirouSettings.UseKeyBoardKey = true
    getgenv().ShirouSettings.UseMouseKey = false
    getgenv().ShirouSettings.ThirdPerson = true
    getgenv().ShirouSettings.FirstPerson = true
    getgenv().ShirouSettings.UseCircleRadius = true
    getgenv().ShirouSettings.DisableOutSideCircle = false
    getgenv().ShirouSettings.Horizontal.PredictMovement = true --// leave on or autoprediction/prediction wont work
    getgenv().ShirouSettings.Part.CheckIfJumped = true
    getgenv().ShirouSettings.Check.CheckIfKo = true -- This Is For Da Hood
    getgenv().ShirouSettings.Check.DisableOnTargetDeath = true --// disables when enemy dies.
    getgenv().ShirouSettings.Check.DisableOnPlayerDeath = true --// disables when you die.
    getgenv().ShirouSettings.Smooth.EnableSmoothness = true
    getgenv().ShirouSettings.Smooth.SmoothMethod = Enum.EasingStyle.Circular
    getgenv().ShirouSettings.Smooth.SmoothMethodV2 = Enum.EasingDirection.InOut
    getgenv().ShirouSettings.Resolver.UnderGround = true
    getgenv().ShirouSettings.Resolver.UseUnderGroundKeybind = false
    getgenv().ShirouSettings.Resolver.UnderGroundKey = Enum.KeyCode.K
    getgenv().ShirouSettings.Resolver.DetectDesync = true
    getgenv().ShirouSettings.Resolver.Detection = 55
    getgenv().ShirouSettings.Resolver.UseDetectDesyncKeybind = false
    getgenv().ShirouSettings.Resolver.DetectDesyncKey = Enum.KeyCode.L
    getgenv().ShirouSettings.Resolver.SendNotification = false
    getgenv().ShirouSettings.FovTransparency = 1
    getgenv().ShirouSettings.FovThickness = 1
    getgenv().ShirouSettings.FovColor = Color3.fromRGB(0, 0, 0)
    getgenv().ShirouSettings.FovRadius = 360
